[versions]
minecraft = "1.21.1"
yarn_mappings = "1.21.1+build.3"
fabric_loader = "0.16.14"
loom = "1.17-SNAPSHOT"
mixin_squared = "0.2.0"
sodium = "mc1.21.1-0.8.12-fabric"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
mixin_squared = { module = "com.github.bawnorton.mixinsquared:mixinsquared-fabric", version.ref = "mixin_squared" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
