[versions]
minecraft = "26.3"
fabric_loader = "0.19.5"
loom = "1.17-SNAPSHOT"
mixin_squared = "0.2.0"
sodium = "mc26.3-0.9.2-fabric"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
mixin_squared = { module = "com.github.bawnorton.mixinsquared:mixinsquared-fabric", version.ref = "mixin_squared" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
